controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

users_list:
  path: /api/v1/users
  controller: App\Controller\UserController::getUsers
  methods: [GET]
